#!/usr/local/bin/perl
# -*- perl -*-
# 
# Title:            2col.pl
# 
# Description:
# 
# 	
# 
# Notes:
# 
# Programmer:	    Paul Houghton - (paul_houghton@wiltel.com)
# 
# Start Date:	    7/2/95
# 
# Modification History:
#
# $Id$
#
# $Log$
# Revision 1.1  1995/11/16 14:32:54  houghton
# Initial Version.
#
# 


$line_count = 43;

$ln = 0;

for($ln = 0; <> ; $ln++)
{
  chop($_);
  if($ln < ($line_count * 1))
    {
      $col1[$ln % $line_count] = $_;
      next;
    }
  if($ln < ($line_count * 2))
    {
      $col2[$ln % $line_count] = $_;
      next;
    }
}

for($line = 0; $line < $line_count; $line++)
{
  printf("  %-35s %-35s\n",
	 $col1[$line],
	 $col2[$line]);
}
