#!/usr/local/bin/perl
# -*- perl -*-
# 
# Title:            baselist.pl
# 
# Description:
# 
# 	
# 
# Notes:
# 
# Programmer:	    Paul Houghton - (paul_houghton@wiltel.com)
# 
# Start Date:	    12/29/94
# 
# Modification History:
#
# $Id$
#
# $Log$
# Revision 1.1  1995/11/16 14:32:56  houghton
# Initial Version.
#
# 

while(<STDIN>)
{
  if( m#./([^/\n]+)# )
     { 
       if( $1 eq $ARGV[0] )
	 {
	   $found = 1;
	   print "$_"; 
          }
       else
         {
 	   if( $found )
	     { 
	       exit;
	     }
	 }
       
       
     }
   }
}
