#!/usr/local/bin/perl
# -*- perl -*-
# 
# Title:            maxwidth.pl
# 
# Description:
# 
# 	
# 
# Notes:
# 
# Programmer:	    Paul Houghton - (paul_houghton@wiltel.com)
# 
# Start Date:	    11/14/91
# 
# Modification History:
#
# $Id$
#
# $Log$
# Revision 1.1  1995/11/16 14:33:00  houghton
# Initial Version.
#
# 



while(<>)
{
  s/\t/        /g;
  if(length > $max)
    {
      $max = length($_);
    }
}

print "Max Columns: ",$max,"\n";
