#!/usr/local/bin/perl
# -*- perl -*-
# 
# Title:            nextdir.pl
# 
# Description:
# 
# 	
# 
# Notes:
# 
# Programmer:	    Paul Houghton - (paul_houghton@wiltel.com)
# 
# Start Date:	    12/29/94
# 
# Modification History:
#
# $Id$
#
# $Log$
# Revision 1.1  1995/11/16 14:33:01  houghton
# Initial Version.
#
# 




while(<STDIN>)
{
  if( m#./$ARGV[0]/([^/\n]+)# )
     { 
       if( $1 ne $prev )
	 {
	   print "$1\n"; 
	 }
       $prev = $1;
     }
   }
}
