#!/usr/local/bin/perldb

#
# showtables - report tables in a database
#
# Usage: showtables dbname
#
# $Id$
#
# $Log$
# Revision 1.1  1992/01/23 01:34:32  paulh
# Initial revision
#
#

$dbname = $ARGV[0];

$DB_MSG_REPORT = 1;

&set_db($dbname,"sa");

($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);

$today = sprintf("%02d%02d%02d.%02d%02d%02d",
	$year % 100,
	$mon + 1,
	$mday,
	$hour,
	$min,
	$sec);

&send_sql("select o.name, u.name, o.id\n",
	"from sysobjects o, sysusers u\n",
	"where o.type = 'U' and u.uid = o.uid\n",
	"order by o.name\n");

print	"/*\n",
		" * User Table create scripts - generated by 'tablescripts.pl'\n",
		" *\n",
		" * Database: $dbname\n",
		" *\n",
		" * $today\n",
		" */\n";


	@nul = ('NOT NULL','NULL');

while((@tab = &get_record()))
    {
	&send_sql(
		"select Column_name = c.name, \n",
		"       Type = t.name, \n",
		"       Length = c.length, \n",
		"       Nulls = convert(bit, (c.status & 8))\n",
		"from   syscolumns c, systypes t\n",
		"where  c.id = $tab[2]\n",
		"and    c.usertype *= t.usertype\n");
	
	print "\nCREATE TABLE TABLE $dbname.$tab[1].$tab[0]\n\t(\n"; 

	while((@field = &get_record()))
		{
		
		if ($field[1] =~ /char|binary/)
			{
			$dbtype = $field[1] . "(" . $field[2] . ")";
			}
		else
			{
			$dbtype = $field[1];
			}
	
		printf("\t%-30s  %-35s  %s,\n",$field[0],$dbtype,$nul[$field[3]]);
		}
	print ") on 'default'\n";
	}
